### ISSUE TITLE
Increase minimum QGIS version to 2.4

### ISSUE THREAD

**Issue by anitagraser** [ccrook/QGIS-Contour-Plugin#13]
As documented in http://gis.stackexchange.com/questions/152305/why-does-the-contour-plugin-failt-to-load-in-qgis-valmiera/152444#152444

```
AttributeError: 'module' object has no attribute 'QgsFieldExpressionWidget'
```

QgsFieldExpressionWidget seems to first appear in 2.4

**Comment by ccrook** [comment]
Hi Anita

Thanks for pointing this out.  I've updated the QGIS minimum version, and removed one other version with an incorrect QGIS minimum version.  So I think that the remaining versions are correct in terms of the minimum QGIS version required.

Cheers
Chris
________________________________________

**Comment by ccrook** [comment]
Closing stale issue
