### ISSUE TITLE
u'\xe4'

### ISSUE THREAD

**Issue by mamuhaj** [ccrook/QGIS-Contour-Plugin#14]
Hi,

I get the following error message:

Traceback (most recent call last):
  File "C:/Users/Mathias/.qgis2/python/plugins\contour\contour.py", line 476, in accept
    self.makeContours()
  File "C:/Users/Mathias/.qgis2/python/plugins\contour\contour.py", line 677, in makeContours
    clayer =  self.buildContourLayer(lines)
  File "C:/Users/Mathias/.qgis2/python/plugins\contour\contour.py", line 889, in buildContourLayer
    name = "%s"%str(self.uOutputName.text())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 22: ordinal not in range(128)

Python-Version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS-Version:
2.6.0-Brighton Brighton, exported

--

u'\xe4' means the German "ä".

The data-layer do not have any "ä" nor in the field names nether in the data.

What can I do to run your plugin?

Thanks and best Regards

Mathias

**Comment by ccrook** [comment]
Mathias ... The name is coming from the layer name proposed for the contour layer in the contour dialog.   There are a couple of places in the plugin which assumed an ASCII character set.  I've uploaded a new version of the plugin, 1.3.5, which hopefully addresses these.  Let me know if that doesn't fix it for you.

**Comment by mamuhaj** [comment]
Hello Chris,

thank you very much for your help. I ve just tested the new version: it works ! 

Thanks again

Best Regard
Mathias
