### ISSUE TITLE
Calling contour from other modules

### ISSUE THREAD

**Issue by ccrook** [ccrook/QGIS-Contour-Plugin#17]
A user is asking how to call the contour plugin from other plugins.  The current design is not well suited for this as it does not separate user interface from processing functionality.  

It is proposed that it be refactored to do this.  It may be possible to incorporate this into the QGIS processing framework at the same time.

**Comment by gaaraxpo** [comment]
So if someone modified the script to separate UI and processing functionality, people could call the Contour modules from their plugins (or stand-alone app)?

**Comment by ccrook** [comment]
Yes .. that is the thought.  I started looking at it but currently don't have time :-(

**Comment by gaaraxpo** [comment]
What a pity :(
I hope someone would done it

**Comment by gaaraxpo** [comment]
If I inherit the `ContourDialog` Class, give it a name like `contour2` and then override all essential variables (for example: input layer name, data field, number level, min, max, and output layer name). Could I import that child class from my own plugin and use that to interpolate data point?

**Comment by ccrook** [comment]
Hi Fajar

You could do that, though it may make sense to just use the matplotlib functions that the contour plugin is calling https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.tricontour.html or https://matplotlib.org/api/_as_gen/matplotlib.pyplot.contour.html for gridded data.  You could pull out the code from the contour plugin to build geometries from the matplotlib results.

Cheers
Chris
________________________________________

**Comment by gaaraxpo** [comment]
Thank you Mr. Crook. That would more convenient and faster I guess. Alright, I'm going to use matplotlib.pyplot.contour. I think this the part where the plugin uses it:
`cs = plt.contour(gx, gy, gz, levels, extend=extend)`

How to access value of layer's attribute?

**Comment by ccrook** [comment]
For getting the data and getting  contours see

https://github.com/ccrook/QGIS-Contour-Plugin/blob/12ee636ae59555756ba0ab50df844500708343c4/contour/contour.py#L812

For creating the vector layer from them see

https://github.com/ccrook/QGIS-Contour-Plugin/blob/12ee636ae59555756ba0ab50df844500708343c4/contour/contour.py#L929

**Comment by gaaraxpo** [comment]
Thank you for your helpful reply, I'm still trying to workaround it

btw, there is a double declaration of `self._zfield` in here:
https://github.com/ccrook/QGIS-Contour-Plugin/blob/276048aea356806b7b7a7873e30637633daef942/contour/contour.py#L138

and here is the second declaration:
https://github.com/ccrook/QGIS-Contour-Plugin/blob/276048aea356806b7b7a7873e30637633daef942/contour/contour.py#L145

As far as I know, Python treat single and double quotes exactly the same.

**Comment by ccrook** [comment]
Thanks @gaaraxpo - just an oversight.

**Comment by gaaraxpo** [comment]
Do you plan to make the plugin callable in the near future? Because I'm very confused right now :(

**Comment by ccrook** [comment]
@gaaraxpo Plans I've had for a long time - Time to do it ... not yet.  But it's great you have commented on this as it does give me more motivation to do it!

**Comment by gaaraxpo** [comment]
I'm happy hearing that you just get more motivation from me :D

**Comment by ccrook** [comment]
Closing stale issue - contouring now also implemented as processing algorithm that can be called from code
