### ISSUE TITLE
Contour is no more working fine october 2017 ? any other plugin to do the stuff ?

### ISSUE THREAD

**Issue by loicduffar** [ccrook/QGIS-Contour-Plugin#20]
On windows with Qgis 2.14 and 2.18, contour begins to draw something (lines are angular, not smooth like before), but the progress bar stops at 30%.
After closing the box and saving the project, the lines does not appear anymore when loading again (lines was not saved).

It's very disapointing since I didn't found any other plugin to do the job.

**Comment by ccrook** [comment]
Closing stale issue
