### ISSUE TITLE
if the point data has a shape can the contours be made to stay inside the shape?

### ISSUE THREAD

**Issue by karapuzo** [ccrook/QGIS-Contour-Plugin#22]
For instance I have point data for Japan northern island.
I would like the contours to remain inside the point data (i.e. only connect points that are some distance apart or smaller).
Is there a way to do this in the code?

![image](https://user-images.githubusercontent.com/3754054/34896944-5c1b07c4-f7f4-11e7-8f77-14ba724b6bbd.png)

**Comment by ccrook** [comment]
Hi @karapuzo.  The plugin doesn't do this at the moment.  If you have the outline of the area as a polygon you could trim the contours to that polygon after they have been calculated.  Or you could build a polygon by buffering the data points and then using that.  An alternative to trimming I have used for visualisation is to put the polygon layer on top of the contour layer and use the "inverted polygon" renderer to mask out the contours outside the polygon.

**Comment by karapuzo** [comment]
@ccrook  I will give it a try, Thank you.
