### ISSUE TITLE
Plugin crashes in verison 2.18

### ISSUE THREAD

**Issue by palewire** [ccrook/QGIS-Contour-Plugin#24]
As you may have noticed, there are [bug](https://gis.stackexchange.com/questions/259920/why-does-contours-plugin-crash-qgis-2-18) [reports](https://gis.stackexchange.com/questions/231413/error-with-contour-plug-in-qgis-2-18-4) on other platforms for your wonderful library and the latest version of QGIS. 

I tossed in some logging code into my Python console. After I ran the plugin on a few dozen points, with all of the default options selected, QGIS immediately crashed and this was in the log. 

```
$ cat /tmp/qgis.log 
Python warning(1): warning:/home/palewire/.qgis2/python/plugins/contour/contour.py:767: DeprecationWarning: QgsExpression.prepare() is deprecated
  if not expression.prepare(fields):

traceback:  File "/home/palewire/.qgis2/python/plugins/contour/contour.py", line 114, in run
    dlg.exec_()
  File "/home/palewire/.qgis2/python/plugins/contour/contour.py", line 350, in uDataFieldUpdate
    self.reloadData()
  File "/home/palewire/.qgis2/python/plugins/contour/contour.py", line 361, in reloadData
    data=self.getData()
Python warning(1): warning:/home/palewire/.qgis2/python/plugins/contour/contour.py:775: DeprecationWarning: QgsExpression.evaluate() is deprecated
  zval=expression.evaluate(feat)

traceback:  File "/home/palewire/.qgis2/python/plugins/contour/contour.py", line 114, in run
    dlg.exec_()
  File "/home/palewire/.qgis2/python/plugins/contour/contour.py", line 350, in uDataFieldUpdate
    self.reloadData()
  File "/home/palewire/.qgis2/python/plugins/contour/contour.py", line 361, in reloadData
    data=self.getData()
```

**Comment by palewire** [comment]
This is also crashing with [the sample population dataset](https://qgis.org/downloads/data/) provided by QGIS, so I do not think this is problem limited to my input.

**Comment by ccrook** [comment]
@palewire Hi Ben.  Sorry to have been so unresponsive on this.  I was on extended leave in February and somehow lost this in my mail clean up when I returned.  Just seen now!

I have not been able to reproduce this in QGIS 2.18.  I am loading sample data, creating a layer with the ppop data set, and contouring the cat field.  I get some warnings about an invalid geometries and the deprecation warnings, but QGIS is not crashing.  (On the other hand if I try this with QGIS3 it will crash - I don't have a solution to that at present).  

If you are still interested and able to reproduce would you be able to send my the QGIS and platform version info and the exact settings for the contour generation (status of all boxes and set of contour values).  Thanks

**Comment by ccrook** [comment]
Close as stale issue.
