### ISSUE TITLE
Contour Plugin Processing Algorithm not detected in Standalone Script

### ISSUE THREAD

**Issue by gaaraxpo** [ccrook/QGIS-Contour-Plugin#30]
I followed [this script](https://gis.stackexchange.com/a/279937/51131). I was successfully imported the processing algorithms but when I list the algorithms using `print(QgsApplication.processingRegistry().algorithms())`, contour plugin is not listed there (but it listed I tried it in QGIS Python Console) . Is it because it an experimental plugin?

This is what my code looks:
```
sys.path.append('/usr/share/qgis/python/plugins')
import processing
from processing.core.Processing import Processing
Processing.initialize()

print(QgsApplication.processingRegistry().algorithms())
```

I use QGIS 3 on Ubuntu 18

**Comment by ccrook** [comment]
I think the reason is that you haven't registered the plugin processing algorithm.  I think the code would be something like

```
sys.path.append( ... )
from ContourGeneratorProvider import ContourGeneratorProvider
provider=ContourGeneratorProvider()
QgsApplication.processingRegistry().addProvider(self.provider)
```

**Comment by gaaraxpo** [comment]
So the code like this?
```
sys.path.append('/usr/share/qgis/python/plugins')
from ContourGeneratorProvider import ContourGeneratorProvider
provider=ContourGeneratorProvider()
QgsApplication.processingRegistry().addProvider(self.provider)
```
Still get error:
`ModuleNotFoundError: No module named 'ContourGeneratorProvider'`

**Comment by ccrook** [comment]
You could try 

```
sys.path.append('/home/fajar/.local/share/QGIS/QGIS3/profiles/default/python/plugins')
from contour.ContourGeneratorProvider import ContourGeneratorProvider
```

Also I see I have an error in the addProvider line, for self.provider read just provider.

However I suggest it may be more useful to firstly make sure you post the entire code being run and the full error output, as that usually identifies the exact line where this exception is being raised, and secondly to post it to the QGIS user or developer mailing lists where you will get more eyes looking at it.

**Comment by ccrook** [comment]
```
import sys, os
from qgis import core, gui
from qgis.core import QgsApplication
from qgis.PyQt import QtWidgets, QtCore, QtGui, uic
import sys, os

# # Append the path where processing plugin can be found
sys.path.append('/home/fajar/.local/share/QGIS/QGIS3/profiles/default/python/plugins')
from contour.ContourGeneratorProvider import ContourGeneratorProvider
provider=ContourGeneratorProvider()
QgsApplication.processingRegistry().addProvider(provider)
```

**Comment by gaaraxpo** [comment]
Alright this is working, thank you! :D
I was unable to import it because there was a folder named "contour" in the same folder as my script which contained the old contour plugin in QGIS 2.x version. The console didn't tell this.

**Comment by ccrook** [comment]
@gaaraxpo I can't see processing.run() in your code!  Also again a complete error message would be useful.  I suggest writing a script without the GUI to do what you want,  and try and get that going.  Then add the GUI stuff once you have the basic code going.

**Comment by gaaraxpo** [comment]
thank you :D
