### ISSUE TITLE
window size

### ISSUE THREAD

**Issue by jagodki** [ccrook/QGIS-Contour-Plugin#31]
Hi,

the last update seems to contain some GUI changes too. The window is larger then my screen (MBP Mid 2010). The buttons at the bottom are reachable (more or less), but the QgsMessageBar implemented in the plugin-GUI is not readable for me. Maybe it would be better to implement a scroll view, so that the window size could be reduced?

Sincerely,
Christoph
![bildschirmfoto 2018-06-24 um 12 25 35](https://user-images.githubusercontent.com/23242936/41818225-87158b8a-77aa-11e8-941a-2f769ddf7fd4.png)

**Comment by ccrook** [comment]
@jagodki Hi Christoph.  Thanks for feedback - I can see it is an issue for you!  I'll have a look at alternative layouts or scrolling.
