### ISSUE TITLE
Plugin doesn't create first contour

### ISSUE THREAD

**Issue by GIS-Nemo** [ccrook/QGIS-Contour-Plugin#45]
![contour_example](https://user-images.githubusercontent.com/12431940/199580186-1a42bf5e-8819-4677-989c-bd1827a02e8b.jpg)

I have an irregular grid of points, each with a value that ranges from 100 to almost 17000.  The plugin window shows the list of contours it will create, which includes 100.  But, the 100 contour is not created.  Is there something I'm missing in the settings?

**Comment by ccrook** [comment]
Hi.  If there are no values less than 100 then it will not be able to place a contour at 100 - generally it needs data points below and above a contour value to work out where the contour should lie.

**Comment by GIS-Nemo** [comment]
Thanks for the reply.  It doesn't seem to have any problem creating a line for the highest value points...

![two](https://user-images.githubusercontent.com/12431940/199807185-55739b5b-aebb-4bdc-9a17-5a477578efa6.jpg)

**Comment by ccrook** [comment]
Closing this issue as this is expected behaviour of plugin
