### ISSUE TITLE
RuntimeError : wrapped C/C++ object of type ContourGeneratorAlgorithm has been deleted

### ISSUE THREAD

**Issue by dubravat** [ccrook/QGIS-Contour-Plugin#46]
Every time when I change the background colour in QGIS the following error appears

![image](https://user-images.githubusercontent.com/17712182/205440281-59f0e4e0-0cec-4227-9701-5a61ef0395c2.png)

QGIS 3.28 Firenze

**Comment by ccrook** [comment]
@dubravat Fixed in version 2.0.11.  Massive thankyou to Nyall Dawson who exactly identifed the error and offered a fix.
