### ISSUE TITLE
No such table: contour

### ISSUE THREAD

**Issue by singlerider** [ccrook/QGIS-Contour-Plugin#59]
QGIS version: `3.40.1-Bratislava`
Contour Plugin version: `2.0.14 updated at 6/2/2024 11:50 PM -10`

I don't see any documentation, so I don't know if there are some steps required to create a Postgres database manually beforehand. I simply click my raster layer, then the menu options, `Raster` => `Extraction...` => `Contour`. I click "Run" in the Contour plugin-in options and:

```
QGIS version: 3.40.1-Bratislava
Qt version: 5.15.16
Python version: 3.12.7
GDAL version: 3.10.0
GEOS version: 3.13.0-CAPI-1.19.0
PROJ version: Rel. 9.5.0, September 15th, 2024
PDAL version: 2.8.2 (git-version: Release)
Algorithm started at: 2024-12-06T16:42:19
Algorithm 'Contour' starting…
Input parameters:
{ 'BAND' : 1, 'CREATE_3D' : False, 'EXTRA' : '', 'FIELD_NAME' : 'ELEV', 'IGNORE_NODATA' : False, 'INPUT' : '/home/shane/git/exploration/bathymetry/gebco_bathymetry_geotiff/gebco_2024_n90.0_s0.0_w90.0_e180.0.tif', 'INTERVAL' : 10, 'NODATA' : None, 'OFFSET' : 0, 'OUTPUT' : 'TEMPORARY_OUTPUT' }
...
GDAL command:
gdal_contour -b 1 -a ELEV -i 10.0 -off 5.0 -f "GPKG" /home/shane/git/exploration/bathymetry/gebco_bathymetry_1/gebco_2024_n90.0_s0.0_w-180.0_e-90.0.asc /tmp/processing_HjeNFd/d30bc4e5334f4d2783408df67dcd4aac/OUTPUT.gpkg
GDAL command output:
ERROR 1: failed to execute insert : database or disk is full
ERROR 1: cannot write linestring
ERROR 1: failed to prepare SQL: INSERT INTO "contour" ( "geom", "ID", "ELEV") VALUES (?, ?, ?) - no such table: contour
ERROR 1: cannot write linestring
ERROR 1: failed to prepare SQL: INSERT INTO "contour" ( "geom", "ID", "ELEV") VALUES (?, ?, ?) - no such table: contour
...
ERROR 1: cannot write linestring
More than 1000 errors or warnings have been reported. No more will be reported from now.
...
```

To be clear, my disk is not full.

![image](https://github.com/user-attachments/assets/85bb5107-f1db-465f-a153-36f7fef0df7b)

**Comment by singlerider** [comment]
Closing as maybe it's possible this is more related to GDAL than this particular plugin. Either way, I'm confused.

**Comment by ccrook** [comment]
I agree closing the issue for here is correct - the Contour plugin appears in the Vector menu and generates contours from data values on point data.  The raster extraction contours options may be GDAL - I am not familiar with it.  Thanks
